source $VIMRUNTIME/defaults.vim

set splitright
set splitbelow
set hidden

set ignorecase
set smartcase

set clipboard=unnamedplus
set mouse=""

set dir=/tmp

let g:netrw_banner = 0
let g:netrw_liststyle = 3

let g:langTerms = {'python': 'ipython'}

let g:lsc_auto_map = v:true
let g:lsc_server_commands = {
\  "go": {
\    "command": "/home/ilango/go/bin/gopls serve",
\    "log_level": -1,
\    "suppress_stderr": v:true,
\  },
\  "c": "clangd --compile-commands-dir=build --clang-tidy --log=error",
\  "python": "pyls",
\  "sh": "bash-language-server start",
\  "rust": "rust-analyzer",
\  "html": "vscode-html-languageserver --stdio"
\}
