" Load useful defaults
source $VIMRUNTIME/defaults.vim

" Windows
set splitright
set splitbelow
set hidden

" Search
set ignorecase
set smartcase

" Clipboard
set clipboard=unnamedplus

" Swap files
set dir=/tmp

" netrw config
" let g:netrw_banner = 0
" let g:netrw_liststyle = 3
" let g:netrw_browse_split = 2
" Disable netrw
let g:loaded_netrw = 1
let g:netrw_loaded_netrwPlugin = 1

" Color scheme
set termguicolors
set background=dark
colorscheme gruvbox
" This won't work properly with lsc
" autocmd vimenter * ++nested colorscheme gruvbox

" lightline config
set laststatus=2
set noshowmode
let g:lightline = {'colorscheme': 'gruvbox'}

" SendToTerm config
let g:langTerms = {'python': 'ipython'}

" vim-lsc config
let g:lsc_auto_map = v:true
let g:lsc_server_commands = {
\  "go": {
\    "command": $HOME."/go/bin/gopls serve",
\    "log_level": -1,
\    "suppress_stderr": v:true,
\  },
\  "c": "clangd --clang-tidy --log=error",
\  "cpp": "clangd --clang-tidy --log=error",
\  "python": "pyls",
\  "sh": "bash-language-server start",
\  "rust": "rust-analyzer",
\  "html": "vscode-html-languageserver --stdio",
\  "javascript": "typescript-language-server --stdio",
\  "typescript": "typescript-language-server --stdio",
\  "vim" : {
\     "name": "vim-language-server",
\     "command": $HOME."/.npm/bin/vim-language-server --stdio",
\        "message_hooks": {
\            "initialize": {
\                "initializationOptions": { "vimruntime": $VIMRUNTIME, "runtimepath": &rtp },
\            },
\        },
\     },
\  }

" Formatting
augroup formatters
	au!
	au FileType c,cpp setlocal formatprg=clang-format
	au FileType python setlocal formatprg=yapf
	au FileType go setlocal formatprg=gofmt
augroup END
nnoremap <Leader>f mfgggqG`f

" File browsing with split windows
nnoremap <Leader>z :FZF<CR>
nnoremap <Leader>x :Fern . -reveal=%<CR>
