[theme]
name = "gruvbox-dark"

[theme.overrides]
separator = ""

[icons]
name = "awesome6"

[[block]]
block = "net"
format = "{ssid} {ip}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 300
warning = 10.0
alert = 5.0
format = "{icon} {available}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 10

[[block]]
block = "load"
interval = 10
format = "{5m} {1m}"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT1"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
