[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome6"

[[block]]
block = "net"
format = " $ssid $ip "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 300
warning = 10.0
alert = 5.0
format = " $icon $available "

[[block]]
block = "memory"
format = " $icon $mem_avail "

[[block]]
block = "cpu"
interval = 10

[[block]]
block = "load"
interval = 10
format = " $icon $5m.eng(w:4) $1m.eng(w:4) "

[[block]]
block = "music"

[[block]]
block = "sound"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT1"

[[block]]
block = "time"
interval = 5
